In [239]:
#!pip install torch
import torch

In [240]:
data = [[1.0,2.0,3.0], [4.0,5.0,6.0]]
tensor = torch.tensor(data, requires_grad=True)

print(tensor)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.Size([2, 3])
torch.float32
cpu


In [241]:
shape = (2,3)
ones = torch.ones(shape)
zeros = torch.zeros(shape)
random = torch.randn(shape)

print(ones)
print(zeros)
print(random)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[-1.6835,  2.2160,  0.6732],
        [-0.3262, -1.2150, -1.2803]])


In [242]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(4.0, requires_grad=True)
x = torch.tensor(10., requires_grad=True)

y = a + b
z = x * y

print(z)
print(z.grad_fn)

tensor(60., grad_fn=<MulBackward0>)


In [243]:
a = torch.tensor([[1.,2.],[3.,4.]])
b = torch.tensor([[5.,4.],[1.,8.]])

c = a * b
print(c)
print(a.mean(dim=0))
print(a.mean(dim=1))

tensor([[ 5.,  8.],
        [ 3., 32.]])
tensor([2., 3.])
tensor([1.5000, 3.5000])


In [244]:
x = torch.arange(12).reshape(3,4)
col = x[:, 2]
print(x)
print(col)
print(torch.argmax(x, dim=1))
print(torch.gather(x, dim=1, index=torch.tensor([[0], [2], [3]])))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 2,  6, 10])
tensor([3, 3, 3])
tensor([[ 0],
        [ 6],
        [11]])


In [245]:
N = 10
D_in = 1
D_out = 1
X = torch.randn(N,D_in)

true_W = torch.tensor([[2.0]])
true_b = torch.tensor(1.0)
y = X @ true_W + true_b + torch.randn(N, D_out) * 0.1

W = torch.randn(D_in, D_out, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print(f"Init. W: {W}")
print(f"Init. b: {b}")

def model(X):
    return X @ W + b

y_hat = model(X)

print(f"Prediction y hat: {y_hat[:3]}")
print(f"True y: {y[:3]}")

error = y_hat - y
squared_error = error ** 2
loss = squared_error.mean()

print(f"LOSS: {loss}")

loss.backward()
print(W.grad)
print(b.grad)

learning_rate, epochs = 0.01, 1000
W, b = torch.randn(1,1,requires_grad=True), torch.rand(1, requires_grad=True)

for epoch in range(epochs):
    y_hat = X @ W + b
    loss = torch.mean((y_hat - y) ** 2)
    loss.backward()
    with torch.no_grad():
        W -= learning_rate * W.grad
        b -= learning_rate * b.grad
    
    W.grad.zero_()
    b.grad.zero_()
    
    if epoch % 10 == 0:
        print(f'EPOCH: {epoch:02d} \ Loss: {loss.item():.4f}, W: {W.item():.3f}, b: {b.item():.3f}')

print(f'FINAL PARAMETERS: W={W.item():.3f}, b={b.item():.3f}')
print(f'True params: W=2, b=1')


Init. W: tensor([[1.0868]], requires_grad=True)
Init. b: tensor([0.0944], requires_grad=True)
Prediction y hat: tensor([[ 1.2978],
        [-0.6659],
        [ 1.3976]], grad_fn=<SliceBackward0>)
True y: tensor([[ 3.2623],
        [-0.1563],
        [ 3.4464]])
LOSS: 2.2548105716705322
tensor([[-2.1489]])
tensor([-2.6922])
EPOCH: 00 \ Loss: 10.8781, W: -1.547, b: 0.655
EPOCH: 10 \ Loss: 7.0956, W: -1.050, b: 0.994
EPOCH: 20 \ Loss: 4.7807, W: -0.645, b: 1.235
EPOCH: 30 \ Loss: 3.3376, W: -0.311, b: 1.401
EPOCH: 40 \ Loss: 2.4167, W: -0.035, b: 1.512
EPOCH: 50 \ Loss: 1.8119, W: 0.197, b: 1.581
EPOCH: 60 \ Loss: 1.4013, W: 0.392, b: 1.621
EPOCH: 70 \ Loss: 1.1126, W: 0.559, b: 1.638
EPOCH: 80 \ Loss: 0.9020, W: 0.702, b: 1.639
EPOCH: 90 \ Loss: 0.7432, W: 0.826, b: 1.630
EPOCH: 100 \ Loss: 0.6198, W: 0.935, b: 1.612
EPOCH: 110 \ Loss: 0.5216, W: 1.031, b: 1.589
EPOCH: 120 \ Loss: 0.4420, W: 1.115, b: 1.563
EPOCH: 130 \ Loss: 0.3763, W: 1.191, b: 1.536
EPOCH: 140 \ Loss: 0.3217, W: 1.258

<>:49: SyntaxWarning: invalid escape sequence '\ '
<>:49: SyntaxWarning: invalid escape sequence '\ '
C:\Users\Stein\AppData\Local\Temp\ipykernel_4720\218697554.py:49: SyntaxWarning: invalid escape sequence '\ '
  print(f'EPOCH: {epoch:02d} \ Loss: {loss.item():.4f}, W: {W.item():.3f}, b: {b.item():.3f}')


In [246]:
D_in = 1
D_out = 1

linear_layer = torch.nn.Linear(in_features=D_in, out_features=D_out)

print(f'Layers Weight: {linear_layer.weight}')
print(f'Layers bias: {linear_layer.bias}')

y_hatnn = linear_layer(X)

print(f"OUTPUT of linear: {y_hatnn[:3]}")

Layers Weight: Parameter containing:
tensor([[-0.2661]], requires_grad=True)
Layers bias: Parameter containing:
tensor([-0.8872], requires_grad=True)
OUTPUT of linear: tensor([[-1.1818],
        [-0.7010],
        [-1.2062]], grad_fn=<SliceBackward0>)


In [247]:
import torch.nn as nn
import torch.optim as optim

class LinearRegressionModel(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.linear_layer = nn.Linear(in_features, out_features)
    
    def forward(self, x):
        return self.linear_layer(x)

model = LinearRegressionModel(in_features=1, out_features=1)
print(model)
learning_rate = 0.01
optimizer = optim.Adam(model.parameters(), lr=learning_rate)
loss_fn=nn.MSELoss()
epochs = 1000
for epoch in range(epochs):
    y_hat = model(X)
    loss = loss_fn(y_hat, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    print(f"Epoch {epoch:02d} / {epochs} | Loss: {loss.item():.4f}")


LinearRegressionModel(
  (linear_layer): Linear(in_features=1, out_features=1, bias=True)
)
Epoch 00 / 1000 | Loss: 1.7669
Epoch 01 / 1000 | Loss: 1.7251
Epoch 02 / 1000 | Loss: 1.6838
Epoch 03 / 1000 | Loss: 1.6431
Epoch 04 / 1000 | Loss: 1.6029
Epoch 05 / 1000 | Loss: 1.5633
Epoch 06 / 1000 | Loss: 1.5243
Epoch 07 / 1000 | Loss: 1.4859
Epoch 08 / 1000 | Loss: 1.4480
Epoch 09 / 1000 | Loss: 1.4108
Epoch 10 / 1000 | Loss: 1.3741
Epoch 11 / 1000 | Loss: 1.3380
Epoch 12 / 1000 | Loss: 1.3026
Epoch 13 / 1000 | Loss: 1.2677
Epoch 14 / 1000 | Loss: 1.2335
Epoch 15 / 1000 | Loss: 1.1999
Epoch 16 / 1000 | Loss: 1.1669
Epoch 17 / 1000 | Loss: 1.1345
Epoch 18 / 1000 | Loss: 1.1028
Epoch 19 / 1000 | Loss: 1.0717
Epoch 20 / 1000 | Loss: 1.0412
Epoch 21 / 1000 | Loss: 1.0113
Epoch 22 / 1000 | Loss: 0.9821
Epoch 23 / 1000 | Loss: 0.9535
Epoch 24 / 1000 | Loss: 0.9255
Epoch 25 / 1000 | Loss: 0.8981
Epoch 26 / 1000 | Loss: 0.8714
Epoch 27 / 1000 | Loss: 0.8452
Epoch 28 / 1000 | Loss: 0.8197
Epoch 29 