In [181]:
#!pip install torch
import torch

In [182]:
data = [[1.0,2.0,3.0], [4.0,5.0,6.0]]
tensor = torch.tensor(data, requires_grad=True)

print(tensor)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.Size([2, 3])
torch.float32
cpu


In [183]:
shape = (2,3)
ones = torch.ones(shape)
zeros = torch.zeros(shape)
random = torch.randn(shape)

print(ones)
print(zeros)
print(random)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[-0.3561,  0.3919, -0.5935],
        [-0.7443,  0.0166,  0.3884]])


In [184]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(4.0, requires_grad=True)
x = torch.tensor(10., requires_grad=True)

y = a + b
z = x * y

print(z)
print(z.grad_fn)

tensor(60., grad_fn=<MulBackward0>)


In [185]:
a = torch.tensor([[1.,2.],[3.,4.]])
b = torch.tensor([[5.,4.],[1.,8.]])

c = a * b
print(c)
print(a.mean(dim=0))
print(a.mean(dim=1))

tensor([[ 5.,  8.],
        [ 3., 32.]])
tensor([2., 3.])
tensor([1.5000, 3.5000])


In [186]:
x = torch.arange(12).reshape(3,4)
col = x[:, 2]
print(x)
print(col)
print(torch.argmax(x, dim=1))
print(torch.gather(x, dim=1, index=torch.tensor([[0], [2], [3]])))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 2,  6, 10])
tensor([3, 3, 3])
tensor([[ 0],
        [ 6],
        [11]])


In [196]:
N = 10
D_in = 1
D_out = 1
X = torch.randn(N,D_in)

true_W = torch.tensor([[2.0]])
true_b = torch.tensor(1.0)
y = X @ true_W + true_b + torch.randn(N, D_out) * 0.1

W = torch.randn(D_in, D_out, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print(f"Init. W: {W}")
print(f"Init. b: {b}")

def model(X):
    return X @ W + b

y_hat = model(X)

print(f"Prediction y hat: {y_hat[:3]}")
print(f"True y: {y[:3]}")

error = y_hat - y
squared_error = error ** 2
loss = squared_error.mean()

print(f"LOSS: {loss}")

loss.backward()
print(W.grad)
print(b.grad)

learning_rate, epochs = 0.01, 1000
W, b = torch.randn(1,1,requires_grad=True), torch.rand(1, requires_grad=True)

for epoch in range(epochs):
    y_hat = X @ W + b
    loss = torch.mean((y_hat - y) ** 2)
    loss.backward()
    with torch.no_grad():
        W -= learning_rate * W.grad
        b -= learning_rate * b.grad
    
    W.grad.zero_()
    b.grad.zero_()
    
    if epoch % 10 == 0:
        print(f'EPOCH: {epoch:02d} \ Loss: {loss.item():.4f}, W: {W.item():.3f}, b: {b.item():.3f}')

print(f'FINAL PARAMETERS: W={W.item():.3f}, b={b.item():.3f}')
print(f'True params: W=2, b=1')


Init. W: tensor([[-1.2910]], requires_grad=True)
Init. b: tensor([-0.5111], requires_grad=True)
Prediction y hat: tensor([[-1.0922],
        [-1.8029],
        [ 0.4534]], grad_fn=<SliceBackward0>)
True y: tensor([[ 1.9382],
        [ 2.9751],
        [-0.5206]])
LOSS: 13.552383422851562
tensor([[-6.9616]])
tensor([-2.7983])
EPOCH: 00 \ Loss: 0.1588, W: 1.663, b: 0.830
EPOCH: 10 \ Loss: 0.1079, W: 1.724, b: 0.865
EPOCH: 20 \ Loss: 0.0744, W: 1.773, b: 0.894
EPOCH: 30 \ Loss: 0.0522, W: 1.813, b: 0.918
EPOCH: 40 \ Loss: 0.0375, W: 1.844, b: 0.938
EPOCH: 50 \ Loss: 0.0277, W: 1.870, b: 0.955
EPOCH: 60 \ Loss: 0.0213, W: 1.891, b: 0.968
EPOCH: 70 \ Loss: 0.0170, W: 1.908, b: 0.980
EPOCH: 80 \ Loss: 0.0142, W: 1.921, b: 0.989
EPOCH: 90 \ Loss: 0.0123, W: 1.932, b: 0.997
EPOCH: 100 \ Loss: 0.0111, W: 1.941, b: 1.003
EPOCH: 110 \ Loss: 0.0102, W: 1.948, b: 1.009
EPOCH: 120 \ Loss: 0.0097, W: 1.954, b: 1.013
EPOCH: 130 \ Loss: 0.0093, W: 1.959, b: 1.017
EPOCH: 140 \ Loss: 0.0091, W: 1.963, b:

<>:49: SyntaxWarning: invalid escape sequence '\ '
<>:49: SyntaxWarning: invalid escape sequence '\ '
C:\Users\Stein\AppData\Local\Temp\ipykernel_4720\218697554.py:49: SyntaxWarning: invalid escape sequence '\ '
  print(f'EPOCH: {epoch:02d} \ Loss: {loss.item():.4f}, W: {W.item():.3f}, b: {b.item():.3f}')
